language: node_js
os: linux
node_js:
- '14'
deploy:
  provider: npm
  edge: true
  email: "$NPM_EMAIL"
  api_token: "$NPM_TOKEN"
  cleanup: false
  on:
    branch: master
    tags: true
    repo: bisand/node-red-contrib-msnodesql
